import QtQuick

QtObject {
    readonly property color appBackground: "#111318"
    readonly property color canvasBackground: "#181a20"
    readonly property color gridMinor: "#343846"
    readonly property color gridMajor: "#4a5062"
    readonly property color gridAxis: "#6a7186"
    readonly property color textMain: "#d7dbe3"
    readonly property color textMuted: "#8d94a3"
    readonly property color menuBarBackground: "#20232b"
    readonly property color menuBarBorder: "#2c313d"
    readonly property color menuButtonHover: "#343946"
    readonly property color accent: "#f5a742"
    readonly property color nodeBackground: "#2b2b2b"
    readonly property color nodeHeaderBackground: "#1f1f1f"
    readonly property color nodeSocket: "#1fc7a6"
    readonly property color nodeControlBackground: "#edf2f7"
    readonly property color nodeControlText: "#111318"
    readonly property color nodeControlBorder: "#6f8fb0"
    readonly property color infoBarBackground: "#20232b"
    readonly property color infoBarBorder: "#2c313d"
    readonly property color overlayBackground: "#00000066"
    readonly property color panelBorder: "#3f424c"
}
